# run these commands exactly one line after another in powershell
# Set-ExecutionPolicy RemoteSigned -Scope Process
# .\DownloadMods.ps1


# === Configuration ===
$modUrls = @(
"https://cdn.modrinth.com/data/P7dR8mSH/versions/PB9Kjpo3/fabric-api-0.92.5%2B1.20.1.jar" 
"https://cdn.modrinth.com/data/AANobbMI/versions/OihdIimA/sodium-fabric-0.5.13%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/mOgUt4GM/versions/lEkperf6/modmenu-7.2.2.jar"
"https://cdn.modrinth.com/data/uXXizFIs/versions/unerR5MN/ferritecore-6.0.1-fabric.jar"
"https://cdn.modrinth.com/data/gvQqBUqZ/versions/vuuAe7ZA/lithium-fabric-mc1.20.1-0.11.3.jar"
"https://cdn.modrinth.com/data/NNAgCjsB/versions/xuiHEnFJ/entityculling-fabric-1.7.4-mc1.20.1.jar"
"https://cdn.modrinth.com/data/5ZwdcRci/versions/6QvRWWbF/ImmediatelyFast-Fabric-1.5.0%2B1.20.4.jar"
"https://cdn.modrinth.com/data/nmDcB62a/versions/srmUM7tY/modernfix-fabric-5.21.0%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/shFhR8Vx/versions/Ur9uoHH5/Better%20MC%20%5BFABRIC%5D%20-%20BMC2%20v26.5.mrpack"
# "https://cdn.modrinth.com/data/uCdwusMi/versions/vSDePnsB/DistantHorizons-fabric-forge-2.3.2-b-1.20.1.jar"
"https://cdn.modrinth.com/data/g96Z4WVZ/versions/5kAwHDZz/BadOptimizations-2.2.2-1.20.1.jar"
# "https://cdn.modrinth.com/data/Orvt0mRa/versions/nQHYSjxO/indium-1.0.36%2Bmc1.20.1.jar"
# better minecraft mods below
"https://cdn.modrinth.com/data/1s5x833P/versions/r5OGe9iP/Neruina-2.2.4-fabric%2B1.20.1.jar"
"https://cdn.modrinth.com/data/HVnmMxH1/versions/71Hn3myZ/ComplementaryReimagined_r5.3.zip"
"https://cdn.modrinth.com/data/WQ8xE11Z/versions/S1HbCX1t/Repurposed_Structures-Better_Monuments_v6.zip"
"https://cdn.modrinth.com/data/EnPUzSTg/versions/7IsKGDTI/XaeroPlus-2.24.5%2Bfabric-1.20.1-WM1.39.0-MM24.6.1.jar"
"https://cdn.modrinth.com/data/WRaRZdTd/versions/gkqfqi9t/sawmill-1.20-1.4.3-fabric.jar"
"https://cdn.modrinth.com/data/UYd23ZmY/versions/Wd5ik1WC/Repurposed_Structures-Friends_And_Foes_v5.zip"
"https://cdn.modrinth.com/data/sGmHWmeL/versions/1.1.1%2B1.17/mixintrace-1.1.1%2B1.17.jar"
"https://cdn.modrinth.com/data/bHJp2GRg/versions/ctUjPcK0/NetherChested-v8.0.4-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/b1ZV3DIJ/versions/mXJWSwbJ/athena-fabric-1.20.1-3.1.2.jar"
"https://cdn.modrinth.com/data/HH4FjUqN/versions/U5KahCRT/%5B1.20.1%5D%20Hybrid%20Aquatic%201.3.5.jar"
"https://cdn.modrinth.com/data/AANobbMI/versions/ygf8cVZg/sodium-fabric-0.5.11%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/P7dR8mSH/versions/P7uGFii0/fabric-api-0.92.2%2B1.20.1.jar"
"https://cdn.modrinth.com/data/P5wB88AS/versions/DSuBmePz/Repurposed_Structures-Farmers_Delight_v6.zip"
"https://cdn.modrinth.com/data/EldwHO4Z/versions/SJn4GXJb/dragonloot-1.1.4.jar"
"https://cdn.modrinth.com/data/Cnejf5xM/versions/4UWabEWo/right-click-harvest-3.2.3%2B1.19.x-1.20.1-fabric.jar"
"https://cdn.modrinth.com/data/Orvt0mRa/versions/gofbpynL/indium-1.0.34%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/Ae6qoBj3/versions/G35Yb3qU/frostiful-1.0.11.jar"
"https://cdn.modrinth.com/data/eA8SXqWL/versions/tCLd1j4G/the_bumblezone-7.5.5%2B1.20.1-fabric.jar"
"https://cdn.modrinth.com/data/M1953qlQ/versions/PlEObkl9/resourcefulconfig-fabric-1.20.1-2.1.2.jar"
"https://cdn.modrinth.com/data/fuuu3xnx/versions/eh4IBlu2/Searchables-fabric-1.20.1-1.0.3.jar"
"https://cdn.modrinth.com/data/5TWoVsKB/versions/8EHHDKUM/Repurposed_Structures-Chef%27s_Delight_v3.zip"
"https://cdn.modrinth.com/data/HgALhmVM/versions/AITsoSM2/NightConfigFixes-v8.0.0-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/RfFxanNh/versions/BbFqiKvi/fasterrandom-5.1.0.jar"
"https://cdn.modrinth.com/data/I0UYcPa0/versions/ed738xvb/inmis-2.7.2-1.20.1.jar"
"https://cdn.modrinth.com/data/RG50cUrX/versions/aJj6NXkv/twigs-3.1.0-fabric.jar"
"https://cdn.modrinth.com/data/Eldc1g37/versions/Gob4d0A8/tcdcommons-3.12.3%2Bfabric-1.20.1.jar"
"https://cdn.modrinth.com/data/5ZwdcRci/versions/eUAoLISt/ImmediatelyFast-Fabric-1.3.2%2B1.20.4.jar"
"https://cdn.modrinth.com/data/IKARgflD/versions/eJNY2Ah4/DiagonalFences-v8.1.5-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/ePCzRQkj/versions/wjCAzw7g/hearth_and_home-fabric-1.20.1-2.0.3.jar"
"https://cdn.modrinth.com/data/Fb4jn8m6/versions/NrtzFkZE/FallingTree-1.20.1-4.3.4.jar"
"https://cdn.modrinth.com/data/ayPU0OHc/versions/oUV7mBwk/structure_layout_optimizer-fabric-1.0.2.jar"
"https://cdn.modrinth.com/data/meZK2DCX/versions/J6b05anw/dawn-5.0.0.jar"
"https://cdn.modrinth.com/data/ulloLmqG/versions/YKKY0UDo/another_furniture-fabric-1.20.1-3.0.1.jar"
"https://cdn.modrinth.com/data/jSV9w0J5/versions/jDTECOMb/IllagerInvasion-v8.0.6-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/cVNW5lr6/versions/vyEyvJgV/Highlighter-1.20.1-fabric-1.1.9.jar"
"https://cdn.modrinth.com/data/9TbXlAut/versions/ameSyBNI/thermoo-2.3.3.jar"
"https://cdn.modrinth.com/data/KuNKN7d2/versions/erSJnRcq/noisium-fabric-2.3.0%2Bmc1.20-1.20.1.jar"
"https://cdn.modrinth.com/data/XCIMrYn0/versions/pASfBwdH/Hearths%20v1.0.1%20f12-48.jar"
"https://cdn.modrinth.com/data/tPe4xnPd/versions/F4xBttNI/formations-1.0.3-fabric-mc1.20.2.jar"
"https://cdn.modrinth.com/data/5aaWibi9/versions/AHxQGtuC/trinkets-3.7.2.jar"
"https://cdn.modrinth.com/data/qQyHxfxd/versions/HeZZR2kF/NoChatReports-FABRIC-1.20.1-v2.2.2.jar"
"https://cdn.modrinth.com/data/oHGMwNDR/versions/Tl5Kx50I/VillagersPlus_3.1_%28FABRIC%29_for_1.20.1.jar"
"https://cdn.modrinth.com/data/Yg1VT27P/versions/s6tyjlhX/sodiumoptionsmodcompat-fabric-1.0.0-1.20.1.jar"
"https://cdn.modrinth.com/data/klXONLDA/versions/Ob1PnUNR/villagesandpillages-fabric-mc1.20.1-1.0.2.jar"
"https://cdn.modrinth.com/data/boFjx9eY/versions/m2RpZi3X/Stony%20Cliffs%20for%20Lithostitched%20v1.1.2.jar"
"https://cdn.modrinth.com/data/yWSAtnfH/versions/xY7jTWGb/BHMenu-Fabric-1.20.1-2.4.1.jar"
"https://cdn.modrinth.com/data/Eeb4VkF6/versions/FtCpv6D4/Grass_Overhaul-Fabric-23.10.11-MC1.20.1.jar"
"https://cdn.modrinth.com/data/Wb5oqrBJ/versions/fKY4vKuA/chat_heads-0.13.7-fabric-1.20.jar"
"https://cdn.modrinth.com/data/QmTVMKNG/versions/E4nLamkA/betterend-crashed-ships-1.0.0.jar"
"https://cdn.modrinth.com/data/5faXoLqX/versions/AiO84cp2/Iceberg-1.20.1-fabric-1.1.25.jar"
"https://cdn.modrinth.com/data/DjLobEOy/versions/7ZwnSrVW/Towns-and-Towers-1.12-Fabric%2BForge.jar"
"https://cdn.modrinth.com/data/Ua7DFN59/versions/lscV1N5k/YungsApi-1.20-Fabric-4.0.6.jar"
"https://cdn.modrinth.com/data/T3yEYSUT/versions/XTvbSFNh/Luna-FABRIC-MC1.19.X-1.0.1.jar"
"https://cdn.modrinth.com/data/67kVxsaO/versions/IWpydKCV/lmft-1.0.2%2B1.20-fabric.jar"
"https://cdn.modrinth.com/data/PtjYWJkn/versions/I7ggF6B5/sodium-extra-0.5.4%2Bmc1.20.1-build.115.jar"
"https://cdn.modrinth.com/data/vuWNr14n/versions/4VeEKlR8/keybind_fix-1.0.0.jar"
"https://cdn.modrinth.com/data/mSQF1NpT/versions/7w60aZYA/elytraslot-fabric-6.4.4%2B1.20.1.jar"
"https://cdn.modrinth.com/data/c7m1mi73/versions/djNw6g8u/packetfixer-fabric-1.4.2-1.19-to-1.20.1.jar"
"https://cdn.modrinth.com/data/EjXcpmEA/versions/2CpnF7bC/YouShallNotSpawn-fabric-1.20.x-2.0.2.jar"
"https://cdn.modrinth.com/data/j3FONRYr/versions/fTl6NfPL/Structory_Towers_1.20.x_v1.0.7.jar"
"https://cdn.modrinth.com/data/Wnxd13zP/versions/hefSwtn6/Clumps-fabric-1.20.1-12.0.0.4.jar"
"https://cdn.modrinth.com/data/rex9wwpz/versions/Cjjsdx4e/spawn-1.0.3-fabric.jar"
"https://cdn.modrinth.com/data/P1Kv5EAO/versions/bgc6xYvl/Necronomicon-Fabric-1.6.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/NRjRiSSD/versions/5xvCCRjJ/memoryleakfix-fabric-1.17%2B-1.1.5.jar"
"https://cdn.modrinth.com/data/t5FRdP87/versions/lYpHN3iF/YungsBetterWitchHuts-1.20-Fabric-3.0.3.jar"
"https://cdn.modrinth.com/data/Dk6su9JN/versions/UdH7Njsc/CutThrough-v8.0.2-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/IYY9Siz8/versions/vVYtBiuW/jamlib-0.6.1%2B1.20.x.jar"
"https://cdn.modrinth.com/data/xv94TkTM/versions/6ipZLQSK/Controlling-fabric-1.20.1-12.0.2.jar"
"https://cdn.modrinth.com/data/x9tvGmvR/versions/hA07h7mv/mythic_charms-1.2.2.jar"
"https://cdn.modrinth.com/data/1eAoo2KR/versions/nYfjbBJd/YetAnotherConfigLib-3.6.1%2B1.20.1-fabric.jar"
"https://cdn.modrinth.com/data/EMl3XyUs/versions/nifo2OxY/eden-ring-20.1.20.jar"
"https://cdn.modrinth.com/data/EOig9U0j/versions/tCw8RpfZ/BarteringStation-v8.0.0-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/kkmrDlKT/versions/FZV63yhg/TerraBlender-fabric-1.20.1-3.0.1.7.jar"
"https://cdn.modrinth.com/data/Z2mXHnxP/versions/FL88RLRu/YungsBetterNetherFortresses-1.20-Fabric-2.0.6.jar"
"https://cdn.modrinth.com/data/vevAjqG0/versions/Jq4UH8La/ijmtweaks-1.4.0%2B1.20.jar"
"https://cdn.modrinth.com/data/H8CaAYZC/versions/XGIsoVGT/starlight-1.1.2%2Bfabric.dbc156f.jar"
"https://cdn.modrinth.com/data/r3VgI4QN/versions/S2mz6cYu/reacharound%2B1.20-1.3.1.jar"
"https://cdn.modrinth.com/data/68kWHuUF/versions/bEdg7gJy/universal_ores-1.5.2.jar"
"https://cdn.modrinth.com/data/ziOp6EO8/versions/CtEbg5dY/Corgilib-Fabric-1.20.1-4.0.3.2.jar"
"https://cdn.modrinth.com/data/8pcjMDgj/versions/Xc6BwCFB/TradingPost-v8.0.2-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/BpwWFOVM/versions/E9PUxeM9/Bountiful-6.0.4%2B1.20.1-fabric.jar"
"https://cdn.modrinth.com/data/uJ0YMl4f/versions/Mk16m8e6/Repurposed_Structures-Better_Strongholds_v5.zip"
"https://cdn.modrinth.com/data/XVnUIUAQ/versions/Wm7ocjvH/SnowUnderTrees-2.5.4%2B1.20.1.jar"
"https://cdn.modrinth.com/data/gF3BGWvG/versions/m6dxUHdm/open-parties-and-claims-fabric-1.20.1-0.23.4.jar"
"https://cdn.modrinth.com/data/ZX66K16c/versions/sdb70E1E/PickUpNotifier-v8.0.0-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/pvcsfne4/versions/hV0Pl3WP/chefs-delight-1.0.3-fabric-1.20.1.jar"
"https://cdn.modrinth.com/data/pJmCFF0p/versions/NRw0CDAc/handcrafted-fabric-1.20.1-3.0.6.jar"
"https://cdn.modrinth.com/data/KdJhOYVV/versions/jLHLFjce/Philips-Ruins1.20.1-4.6%5BFabric%5D.jar"
"https://cdn.modrinth.com/data/blWBX5n1/versions/thTIgDLT/forcecloseloadingscreen-2.1.1.jar"
"https://cdn.modrinth.com/data/4EakbH8e/versions/QXYNitXw/farmers-delight-fabric-1.4.3.jar"
"https://cdn.modrinth.com/data/d6GPje96/versions/1DlF1Y4p/autoslabs-1.1.3.jar"
"https://cdn.modrinth.com/data/fnAffV0n/versions/JcDkzJzw/deeperdarker-fabric-1.20-1.3.2.1.jar"
"https://cdn.modrinth.com/data/iJNje1E8/versions/POmpo1V9/SnowRealMagic-1.20.1-Fabric-10.5.4.jar"
"https://cdn.modrinth.com/data/Jqgb3e3H/versions/Kp9eSZNt/AutoslabsCompat.zip"
"https://cdn.modrinth.com/data/Ht4BfYp6/versions/hvfjXu8d/YungsBridges-1.20-Fabric-4.0.3.jar"
"https://cdn.modrinth.com/data/BkTdFBUU/versions/w3Pxx3b4/Pastel-Shaders-Universal-v1.200.zip"
"https://cdn.modrinth.com/data/zFCKsjVY/versions/gOeBY3U6/dynamictrim-1.4.1-fabric%2B1.20.1.jar"
"https://cdn.modrinth.com/data/FzyTKtVF/versions/t4FwBQrZ/Stoneworks-v8.0.0-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/WhbRG4iK/versions/flPXaySR/fallingleaves-1.15.6%2B1.20.1.jar"
"https://cdn.modrinth.com/data/qyVF9oeo/versions/MmKSrFU9/sound-physics-remastered-fabric-1.20.1-1.4.5.jar"
"https://cdn.modrinth.com/data/W3QK7DQz/versions/CgdY86YT/VanillAA.zip"
"https://cdn.modrinth.com/data/YL57xq9U/versions/Bi9nvICq/iris-1.7.5%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/XaDC71GB/versions/AUv5Zp46/lithostitched-fabric-1.20.1-1.3.8.jar"
"https://cdn.modrinth.com/data/aKCwCJlY/versions/FkaSuQb0/Structory_1.20.x_v1.3.5.jar"
"https://cdn.modrinth.com/data/vuGFx44e/versions/o4CYZoEP/ToolStats-Fabric-1.20.1-16.0.9.jar"
"https://cdn.modrinth.com/data/F8BQNPWX/versions/dMGBsRgz/naturalist-fabric-4.0.3-1.20.1.jar"
"https://cdn.modrinth.com/data/HY0PMpa3/versions/nHOjTavv/AutochefsDelight-1.20.1-Fabric-1.0.4.jar"
"https://cdn.modrinth.com/data/Q8xUICr6/versions/Cc4WFedk/ash_api-fabric-3.0.2%2B1.20.1.jar"
"https://cdn.modrinth.com/data/UMmSTwE0/versions/uVqeOjPT/blossom-blade-1.2.jar"
"https://cdn.modrinth.com/data/Hcy2DFKF/versions/QRV0K267/YungsMenuTweaks-1.20.1-Fabric-1.0.2.jar"
"https://cdn.modrinth.com/data/rI0hvYcd/versions/uhvQD6Ny/visuality-0.7.1%2B1.20.jar"
"https://cdn.modrinth.com/data/gc8OEnCC/versions/7QwyTILr/better-end-4.0.11.jar"
"https://cdn.modrinth.com/data/SCAopByd/versions/LwiSX3us/SimpleDiscordRichPresence-fabric-4.0.3-build.40%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/nmDcB62a/versions/qIu7zOc4/modernfix-fabric-5.19.5%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/OMiCHIwt/versions/liAgrvFi/voidz-1.0.11.jar"
"https://cdn.modrinth.com/data/qwvI41y9/versions/RCqdXzHa/sparsestructures-fabric-1.20.1-2.2.0.jar"
"https://cdn.modrinth.com/data/nU0bVIaL/versions/Y6tuH1cn/Patchouli-1.20.1-84-FABRIC.jar"
"https://cdn.modrinth.com/data/Wq5SjeWM/versions/XnYGeBPl/fancymenu_fabric_3.3.2_MC_1.20.1.jar"
"https://cdn.modrinth.com/data/IKpsG0nF/versions/IJLX3k9B/paradise-lost-2.2.4-beta%2B1.20.0.jar"
"https://cdn.modrinth.com/data/RSeLon5O/versions/ryjPL8AJ/particle_core-0.2.5%2B1.20.1.jar"
"https://cdn.modrinth.com/data/9s6osm5g/versions/2xQdCMyG/cloth-config-11.1.136-fabric.jar"
"https://cdn.modrinth.com/data/x5iQ3NM5/versions/Vq76oaXQ/toms_trading_network-fabric-1.20-0.3.0.jar"
"https://cdn.modrinth.com/data/kt3BLgXB/versions/S8KkpB4v/bygonenether-1.20-1.3.2.jar"
"https://cdn.modrinth.com/data/o1C1Dkj5/versions/nidyvq2m/YungsBetterDungeons-1.20-Fabric-4.0.4.jar"
"https://cdn.modrinth.com/data/7vxePowz/versions/vXPVU0EZ/FarmersDelight-1.20.1-2.2.0%2Brefabricated.jar"
"https://cdn.modrinth.com/data/nvQzSEkH/versions/bwDoSE9Z/Jade-1.20-fabric-11.11.0.jar"
"https://cdn.modrinth.com/data/4RdRpt7i/versions/W1oKvY0T/xp_storage-1.5.3%2B1.20.1.jar"
"https://cdn.modrinth.com/data/NcUtCpym/versions/gJ5N7s4J/XaerosWorldMap_1.39.0_Fabric_1.20.jar"
"https://cdn.modrinth.com/data/HjmxVlSr/versions/qLnQnqXS/YungsBetterMineshafts-1.20-Fabric-4.0.4.jar"
"https://cdn.modrinth.com/data/QQXAdCzh/versions/2Y3dASD3/Ping-Wheel-1.10.0-fabric-1.20.1.jar"
"https://cdn.modrinth.com/data/LWGq2eg6/versions/NfqRe01R/Icon%20Xaero%27s%201.14%20HF.zip"
"https://cdn.modrinth.com/data/fPetb5Kh/versions/NovIXDxY/NaturesCompass-1.20.1-2.2.3-fabric.jar"
"https://cdn.modrinth.com/data/ePaZVJM4/versions/Q6deEx42/Repurposed_Structures-Better_Witch_Huts_v4.zip"
"https://cdn.modrinth.com/data/J81TRJWm/versions/RlBGFlWp/konkrete_fabric_1.8.1_MC_1.20.1.jar"
"https://cdn.modrinth.com/data/GuE5FpvB/versions/A5YD9uS3/promenade-4.1.1.jar"
"https://cdn.modrinth.com/data/3IuO68q1/versions/F5UKlslF/puzzle-1.5.2%2B1.20.jar"
"https://cdn.modrinth.com/data/6iTJugQR/versions/jJplEQRv/amendments-1.20-1.2.12-fabric.jar"
"https://cdn.modrinth.com/data/CU0PAyzb/versions/UVPLKCqf/Paxi-1.20-Fabric-4.0.jar"
"https://cdn.modrinth.com/data/gvQqBUqZ/versions/ZSNsJrPI/lithium-fabric-mc1.20.1-0.11.2.jar"
"https://cdn.modrinth.com/data/9Gy8sTXS/versions/VmsNBbCQ/cultural-delights-fabric-1.0.5%2B1.20.1.jar"
"https://cdn.modrinth.com/data/TbriQCWD/versions/3Q4qBNwT/GeckoLibIrisCompat-Fabric-1.0.0.jar"
"https://cdn.modrinth.com/data/PxQSWIcD/versions/QyYBd2yE/sodiumdynamiclights-fabric-1.0.9-1.20.1.jar"
"https://cdn.modrinth.com/data/US6QuKdU/versions/pizP8FAq/DEUF_Refabricated-MC1.20.1-1.1.0.jar"
"https://cdn.modrinth.com/data/AMCbgyVw/versions/uq5F0GNj/Tips-Fabric-1.20.1-12.1.8.jar"
"https://cdn.modrinth.com/data/g96Z4WVZ/versions/M0bM4C3I/BadOptimizations-2.2.1-1.20.1.jar"
"https://cdn.modrinth.com/data/TYRF9nUy/versions/2AjO0Vy9/thermoo-patches-1.0.3.jar"
"https://cdn.modrinth.com/data/ohNO6lps/versions/Qs8LaZLo/ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/bRFWnJ87/versions/WkJeqkhZ/animal_feeding_trough-1.1.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/Ha28R6CL/versions/B0fZidZi/fabric-language-kotlin-1.12.3%2Bkotlin.2.0.21.jar"
"https://cdn.modrinth.com/data/8BmcQJ2H/versions/9VG3hx3F/geckolib-fabric-1.20.1-4.4.9.jar"
"https://cdn.modrinth.com/data/Q2OqKxDG/versions/aefjQSuD/BetterAdvancements-Fabric-1.20.1-0.4.2.10.jar"
"https://cdn.modrinth.com/data/H1JOVjhn/versions/G7rwJQKo/crawl-0.12.0.jar"
"https://cdn.modrinth.com/data/ufdDoWPd/versions/lhlLIEoV/Kiwi-1.20.1-Fabric-11.8.26.jar"
"https://cdn.modrinth.com/data/zp4jb9oQ/versions/IY1tJWHA/transparent-fabric-8.0.1%2B1.20.1.jar"
"https://cdn.modrinth.com/data/kqJFAPU9/versions/h1QpxElt/bettermounthud-1.2.2.jar"
"https://cdn.modrinth.com/data/KJe6y9Eu/versions/sdV8aBn8/fabric-seasons-2.4.2-BETA%2B1.20.jar"
"https://cdn.modrinth.com/data/POQ2i9zu/versions/7H0cR4ue/friendsandfoes-fabric-mc1.20.1-3.0.6.jar"
"https://cdn.modrinth.com/data/Bh6ZOMvp/versions/ceysxHxE/smarterfarmers-1.20-2.1.0-fabric.jar"
"https://cdn.modrinth.com/data/v3CYg2V9/versions/9x0lKayP/drippyloadingscreen_fabric_3.0.8_MC_1.20.1.jar"
"https://cdn.modrinth.com/data/3dT9sgt4/versions/4c00pjbt/YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar"
"https://cdn.modrinth.com/data/twkfQtEc/versions/Hh8niYYN/moonlight-1.20-2.13.33-fabric.jar"
"https://cdn.modrinth.com/data/G1hIVOrD/versions/UOdaYbhh/resourcefullib-fabric-1.20.1-2.1.29.jar"
"https://cdn.modrinth.com/data/cl223EMc/versions/tBnivdbu/cristellib-1.1.5-fabric.jar"
"https://cdn.modrinth.com/data/hYykXjDp/versions/Jf2SIu1T/fzzy_config-0.5.8%2B1.20.1.jar"
"https://cdn.modrinth.com/data/zV5r3pPn/versions/aiPCdDJa/skinlayers3d-fabric-1.7.2-mc1.20.1.jar"
"https://cdn.modrinth.com/data/lhGA9TYQ/versions/WbL7MStR/architectury-9.2.14-fabric.jar"
"https://cdn.modrinth.com/data/codAaoxh/versions/YXz8kIQl/midnightlib-fabric-1.4.1.1.jar"
"https://cdn.modrinth.com/data/WMoUFmXc/versions/azD5oArr/better-trim-tooltips-1.0.1.jar"
"https://cdn.modrinth.com/data/Bh37bMuy/versions/Rc9pkPug/reeses_sodium_options-1.7.2%2Bmc1.20.1-build.101.jar"
"https://cdn.modrinth.com/data/c4aa1Mqq/versions/e74mtqLw/inmisaddon-1.0.4.jar"
"https://cdn.modrinth.com/data/a5ESRz6Q/versions/tJEojbme/Repurposed_Structures-VillagersPlus_v3.zip"
"https://cdn.modrinth.com/data/V8XJ8f5f/versions/ybcBEXlZ/RoughlyEnoughProfessions-fabric-1.20.1-2.0.2.jar"
"https://cdn.modrinth.com/data/pcGnjJ39/versions/EQZmtWsQ/explorations-fabric-1.20.1-1.6.1.jar"
"https://cdn.modrinth.com/data/Gi02250Z/versions/QM6nx1Sa/almanac-1.20.x-fabric-1.0.2.jar"
"https://cdn.modrinth.com/data/OZBR5JT5/versions/pA1enJAS/EasyAnvils-v8.0.2-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/KJhXPbHQ/versions/1Z83Pw2p/BetterCompatibilityChecker-fabric-4.0.8%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/O9C0qdu8/versions/szdkhw2r/quartz-elevator-2.2.7%2B1.20.4.jar"
"https://cdn.modrinth.com/data/yn9u3ypm/versions/66RxRZcI/graves-3.0.3%2B1.20.1.jar"
"https://cdn.modrinth.com/data/3azQ6p0W/versions/jMqsT2VF/cherishedworlds-fabric-6.1.6%2B1.20.1.jar"
"https://cdn.modrinth.com/data/ccKDOlHs/versions/zyOBB7J4/owo-lib-0.11.2%2B1.20.jar"
"https://cdn.modrinth.com/data/KNUSlHiU/versions/Uw0uxYMJ/BetterTridents-v8.0.1-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/uXXizFIs/versions/unerR5MN/ferritecore-6.0.1-fabric.jar"
"https://cdn.modrinth.com/data/UiFDlI7w/versions/yGrKC4Ka/snowyspirit-1.20-3.0.10-fabric.jar"
"https://cdn.modrinth.com/data/e9V6wFcR/versions/4KEfJPHI/expandeddelight-0.3.2.jar"
"https://cdn.modrinth.com/data/oZiSDGCi/versions/bQS4RMW3/fullstackwatchdog-1.0.1%2B1.19.2-fabric.jar"
"https://cdn.modrinth.com/data/kidLKymU/versions/yV6hn0bB/YungsBetterStrongholds-1.20-Fabric-4.0.3.jar"
"https://cdn.modrinth.com/data/BgNRHReB/versions/TPC86Pyz/bclib-3.0.14.jar"
"https://cdn.modrinth.com/data/eiktJyw1/versions/17suT5Mp/everycomp-1.20-2.7.3-fabric.jar"
"https://cdn.modrinth.com/data/DIIgdJzf/versions/ZmhVIn61/EpheroLib-1.20.1-FABRIC-1.2.0.jar"
"https://cdn.modrinth.com/data/SaCpeal4/versions/pMr60Kkq/comforts-fabric-6.4.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/uLbm7CG6/versions/bM6eLTIW/language-reload-1.7.1%2B1.20.1.jar"
"https://cdn.modrinth.com/data/MpzVLzy5/versions/IG7kgtJH/better-nether-9.0.10.jar"
"https://cdn.modrinth.com/data/qUbxpIPN/versions/LruTbLS4/Repurposed_Structures-Better_Dungeons_v5.zip"
"https://cdn.modrinth.com/data/kfqD1JRw/versions/vhuwOiNO/VisualWorkbench-v8.0.0-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/q6eiiQ07/versions/vxRaiz6G/voidtotem-fabric-1.20-3.0.1.jar"
"https://cdn.modrinth.com/data/n6PXGAoM/versions/Ktw36uDC/betterstats-3.12.6%2Bfabric-1.20.1.jar"
"https://cdn.modrinth.com/data/QAGBst4M/versions/qjSRRf2B/PuzzlesLib-v8.1.25-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/MPCX6s5C/versions/dnajXvv1/notenoughanimations-fabric-1.8.1-mc1.20.1.jar"
"https://cdn.modrinth.com/data/t6BIRVZn/versions/FibgWXh0/decorative_blocks-fabric-1.20.1-4.1.3.jar"
"https://cdn.modrinth.com/data/4H6sumDB/versions/jQHHlQiL/EuphoriaPatcher-1.4.3-r5.3-fabric.jar"
"https://cdn.modrinth.com/data/uy4Cnpcm/versions/CBnLZwRS/Bookshelf-Fabric-1.20.1-20.2.13.jar"
"https://cdn.modrinth.com/data/64FYdx5z/versions/RJ4U7Kz1/fabric-seasons-extras-1.3.2-BETA%2B1.20.jar"
"https://cdn.modrinth.com/data/F7wXag4i/versions/iYujfjuN/inventorymanagement-1.3.1%2B1.20.jar"
"https://cdn.modrinth.com/data/hl5OLM95/versions/ahZqcuRr/Geophilic%20v3.1.4%20f15-57.jar"
"https://cdn.modrinth.com/data/joEfVgkn/versions/Mkla4B3q/carryon-fabric-1.20.1-2.1.2.7.jar"
"https://cdn.modrinth.com/data/XZNI4Cpy/versions/9YQrQcI9/toms_storage_fabric-1.20-1.6.8.jar"
"https://cdn.modrinth.com/data/XD7XOrAF/versions/oswQSU19/OverflowingBars-v8.0.1-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/CUfOpYVR/versions/2vRkUyMs/Repurposed_Structures-Bountiful_v3.zip"
"https://cdn.modrinth.com/data/REH0O240/versions/CjrE27Ip/ServerBrowser-1.20.1-FABRIC-1.2.0.jar"
"https://cdn.modrinth.com/data/BUpChT1v/versions/BvZZmYcB/talkbubbles-1.0.8.jar"
"https://cdn.modrinth.com/data/h6zxsNVF/versions/kJrX5B4S/MandalasGUI_Dakmode_Vanilla1.20.4.zip"
"https://cdn.modrinth.com/data/aC3cM3Vq/versions/mjuG4AYd/MouseTweaks-fabric-mc1.20-2.26.jar"
"https://cdn.modrinth.com/data/cGvQGRls/versions/HBTE0lZv/formationsnether-1.0.5.jar"
"https://cdn.modrinth.com/data/9mtu0sUO/versions/G8gwjTTP/fast-ip-ping-v1.0.5-mc1.20.4-fabric.jar"
"https://cdn.modrinth.com/data/BAscRYKm/versions/pwyEaKDs/chipped-fabric-1.20.1-3.0.7.jar"
"https://cdn.modrinth.com/data/zfbCkvdZ/versions/SqVitkHr/Kambrik-6.1.1%2B1.20.1-fabric.jar"
"https://cdn.modrinth.com/data/CVT4pFB2/versions/2o0oW8Yv/melody_fabric_1.0.4_MC_1.20.1-1.20.4.jar"
"https://cdn.modrinth.com/data/rR4tY6Cw/versions/Qcl1PmH5/modpack-update-checker-1.20.1-fabric-0.15.3.jar"
"https://cdn.modrinth.com/data/BdKIyOLe/versions/Q3Z6GESL/Boat-Item-View-Fabric-1.20.1-0.0.5.jar"
"https://cdn.modrinth.com/data/QLPYve8H/versions/ukA6oZlz/NethersDelight-Refabricated-1.20.1-4.1.1.jar"
"https://cdn.modrinth.com/data/4I1XuqiY/versions/jkLvxFFA/entity_model_features_fabric_1.20.1-2.0.2.jar"
"https://cdn.modrinth.com/data/TWsbC6jW/versions/4aO595R4/AdditionalStructures-1.20.x-%28v.4.2.1%29.jar"
"https://cdn.modrinth.com/data/otVJckYQ/versions/8uQeAHwk/citresewn-1.1.5%2B1.20.1.jar"
"https://cdn.modrinth.com/data/bRAPbNyF/versions/PFFXEfYV/veinmining-fabric-1.5.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/defK2XM3/versions/mBYmRou0/adventurez-1.4.20.jar"
"https://cdn.modrinth.com/data/vBbPDuOs/versions/irBBWihm/txnilib-fabric-1.0.19-1.20.1.jar"
"https://cdn.modrinth.com/data/2uEhdGKt/versions/GxBfheVp/EndersDelight-1.20.1-1.0.1.refabricated.jar"
"https://cdn.modrinth.com/data/DOUdJVEm/versions/BtV20YRT/Controlify-2.0.0-beta.10%2B1.20.1.jar"
"https://cdn.modrinth.com/data/jorDmSKv/versions/JCiAyLV3/MagnumTorch-v8.0.2-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/KX1XC0Oo/versions/APtZazrk/formationsoverworld-1.0.4.jar"
"https://cdn.modrinth.com/data/AVq17PqV/versions/I6xyij66/LeavesBeGone-v8.0.0-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/r0v8vy1s/versions/ckuIQWvo/alternate-current-mc1.20-1.9.0.jar"
"https://cdn.modrinth.com/data/BVzZfTc1/versions/3VwlPPf2/entity_texture_features_fabric_1.20.1-6.2.8.jar"
"https://cdn.modrinth.com/data/2BwBOmBQ/versions/qJTsmyiE/YungsBetterEndIsland-1.20-Fabric-2.0.6.jar"
"https://cdn.modrinth.com/data/1IjD5062/versions/84Zs6tNo/continuity-3.0.0-beta.5%2B1.20.1.jar"
"https://cdn.modrinth.com/data/PRN43VSY/versions/M2xzBL7h/animatica-0.6.1%2B1.20.4.jar"
"https://cdn.modrinth.com/data/8Xv7wkWd/versions/Sv5klMQb/Repurposed_Structures-Bygone_Nether_v2.zip"
"https://cdn.modrinth.com/data/SNVQ2c0g/versions/iug2Tybf/MRU-1.0.4%2B1.20.1%2Bfabric.jar"
"https://cdn.modrinth.com/data/ETlrkaYF/versions/KpTt0KNS/cwb-fabric-3.0.0%2Bmc1.20.jar"
"https://cdn.modrinth.com/data/9hx3AbJM/versions/9Jw4urvo/EasyMagic-v8.0.1-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/59rkB3YY/versions/86pJMC8z/guardvillagers-2.0.9-1.20.1.jar"
"https://cdn.modrinth.com/data/e0M1UDsY/versions/aNzU64AT/collective-1.20.1-7.87.jar"
"https://cdn.modrinth.com/data/Z6ykjRlM/versions/4PmfgG4q/spyglass-improvements-1.5.1%2Bmc1.20%2Bfabric.jar"
"https://cdn.modrinth.com/data/tpehi7ww/versions/d1sY0JqV/dungeons-and-taverns-3.0.3.f.jar"
"https://cdn.modrinth.com/data/nPZr02ET/versions/NANcEzKA/netherportalfix-fabric-1.20-13.0.1.jar"
"https://cdn.modrinth.com/data/ckH8gssX/versions/S7xb9dl1/variantcraftingtables-6.4.jar"
"https://cdn.modrinth.com/data/nfn13YXA/versions/nYcMSS03/RoughlyEnoughItems-12.1.785-fabric.jar"
"https://cdn.modrinth.com/data/rLLJ1OZM/versions/7tRnsYkP/coroutil-fabric-1.20.1-1.3.7.jar"
"https://cdn.modrinth.com/data/HSfsxuTo/versions/yRSH0sWM/Explorify%20v1.6.2%20f10-48.jar"
"https://cdn.modrinth.com/data/K01OU20C/versions/qW85eawp/cardinal-components-api-5.2.2.jar"
"https://cdn.modrinth.com/data/vE2FN5qn/versions/i9GmX6sU/letmedespawn-1.20.x-fabric-1.4.4.jar"
"https://cdn.modrinth.com/data/OVb8ZE5p/versions/Uf9jCC3m/BoatBreakFix-Universal-1.0.2.jar"
"https://cdn.modrinth.com/data/uc3VdfLM/versions/dH5N4o0F/farmersknives-3.2.jar"
"https://cdn.modrinth.com/data/rYlnn25U/versions/qQP3RGoX/adorabuild-structures-2.6.0-fabric-1.20.2.jar"
"https://cdn.modrinth.com/data/pzCY6C3e/versions/hynR8fnB/MindfulDarkness-v8.0.3-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/tagwiZkJ/versions/UlzntUUQ/polymorph-fabric-0.49.7%2B1.20.1.jar"
"https://cdn.modrinth.com/data/4VYO7ir0/versions/KIzyS8hk/fabric-seasons-delight-1.3.9-compat-1.0.jar"
"https://cdn.modrinth.com/data/muf0XoRe/versions/MuqUgLqO/repurposed_structures-7.1.15%2B1.20.1-fabric.jar"
"https://cdn.modrinth.com/data/QwxR6Gcd/versions/6XDJoCks/Debugify-1.20.1%2B2.0.jar"
"https://cdn.modrinth.com/data/fQEb0iXm/versions/jiDwS0W1/krypton-0.2.3.jar"
"https://cdn.modrinth.com/data/sTZr7NVo/versions/DZAntbmD/wraith-waystones-3.3.2%2Bmc1.20.1.jar"
"https://cdn.modrinth.com/data/l6YH9Als/versions/XGW2fviP/spark-1.10.53-fabric.jar"
"https://cdn.modrinth.com/data/GZeDW6Px/versions/IhX0ycBe/xpstorage_trinkets-1.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/gsJ6q45e/versions/CJ15oCV4/nicer-skies-1.3.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/9ON3zv6e/versions/IknbjT7v/Log-Begone-Fabric-1.20.1-1.0.8.jar"
"https://cdn.modrinth.com/data/lz0ymQav/versions/txFZVA7O/charm-fabric-1.20.1-forked-6.0.23.jar"
"https://cdn.modrinth.com/data/du3UfiLL/versions/yoCCX4Cc/BOMD-1.7.5-1.20.1.jar"
"https://cdn.modrinth.com/data/YsFycamt/versions/2LDowIR8/ResourcePackOverrides-v8.0.3-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/5WeWGLoJ/versions/nwy63zfI/ForgeConfigScreens-v8.0.2-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/UVtY3ZAC/versions/LeAiyr1s/EnchantmentDescriptions-Fabric-1.20.1-17.1.19.jar"
"https://cdn.modrinth.com/data/mOgUt4GM/versions/lEkperf6/modmenu-7.2.2.jar"
"https://cdn.modrinth.com/data/CFX9ftUJ/versions/KLFf6PpA/advancednetherite-fabric-2.1.3-1.20.1.jar"
"https://cdn.modrinth.com/data/gqRXDo8B/versions/rzXhJ2pH/villagernames-1.20.1-8.1.jar"
"https://cdn.modrinth.com/data/1bokaNcj/versions/jouP2Oob/Xaeros_Minimap_24.6.1_Fabric_1.20.jar"
"https://cdn.modrinth.com/data/SISoSFPP/versions/hOcrPrzr/ConfiguredDefaults-v8.0.1-1.20.1-Fabric.jar"
"https://cdn.modrinth.com/data/b5GyyYkp/versions/bRynnjen/charmofundying-fabric-6.5.0%2B1.20.1.jar"
"https://cdn.modrinth.com/data/CEvDfomf/versions/5tRFmRAm/winterly-0.9.3%2B1.20.jar"
"https://cdn.modrinth.com/data/vqqx0QiE/versions/78EQ9kam/sodiumextras-fabric-1.0.6-1.20.1.jar"
"https://cdn.modrinth.com/data/MBAkmtvl/versions/5sowswPx/balm-fabric-1.20.1-7.3.9.jar"
"https://cdn.modrinth.com/data/z9Ve58Ih/versions/6LPrzuB0/YungsBetterJungleTemples-1.20-Fabric-2.0.5.jar"
"https://cdn.modrinth.com/data/Es5v4eyq/versions/iffT6iAE/sodiumoptionsapi-fabric-1.0.8-1.20.1.jar"
"https://cdn.modrinth.com/data/iG6ZHsUV/versions/4sXZok62/Cull%20Less%20Leaves-1.4.2%2B1.21-fabric.jar"
"https://cdn.modrinth.com/data/DGiq4ZSW/versions/FzmG9oHh/oceansdelight-fdrf-fabric-1.0.2-1.20.jar"
"https://cdn.modrinth.com/data/M08ruV16/versions/2cuVyTav/bobby-5.0.1.jar"
"https://cdn.modrinth.com/data/7uh75ruZ/versions/IDj7kzhS/kleeslabs-fabric-1.20-15.0.0.jar"
)

# Update this to your Minecraft mods folder
$minecraft_directory = "$env:APPDATA\.minecraft"
$modsFolder = "$env:APPDATA\.minecraft\mods"

# Create mods folder if it doesn't exist
if (-not (Test-Path $modsFolder)) {
    New-Item -ItemType Directory -Path $modsFolder | Out-Null
}

# === Download Mods ===
foreach ($url in $modUrls) {
    try {
        $fileName = Split-Path $url -Leaf
        $destination = Join-Path $modsFolder $fileName

        Write-Host "Downloading $fileName..."
        Invoke-WebRequest -Uri $url -OutFile $destination
        Write-Host "Saved to $destination`n"
    }
    catch {
        Write-Warning ("Failed to download " + $url + ": " + $_)
    }

}

# === Extract .mrpack ===
$mrpackFile = Join-Path $modsFolder "Better%20MC%20%5BFABRIC%5D%20-%20BMC2%20v26.5.mrpack"

if (Test-Path $mrpackFile) {
    Write-Host "Extracting $mrpackFile to $minecraft_directory..."
    Expand-Archive -Path $mrpackFile -DestinationPath $minecraft_directory -Force
    Write-Host "Extraction complete."
} else {
    Write-Warning "Could not find the .mrpack file to extract."
}

Write-Host "All done."

